services:
  db:
    image: mysql:8.0
    container_name: grocery-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vadodara@123
      MYSQL_DATABASE: test
      MYSQL_USER: jigxi
      MYSQL_PASSWORD: Vadodara@123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: grocery-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: jigxi
      DB_PASS: Vadodara@123
      DB_NAME: test
    command: sh -c "npm run start"

volumes:
  db_data:
